export const formData = [
  {
    label: '主键ID',
    field: 'kid',
    type: 'hidden',
    value: '',
    desc: '',
    required: false,
    search: true,
  },
  {
    label: '登录名',
    field: 'loginName',
    type: 'text',
    value: '',
    desc: '',
    required: true,
    search: true,
  },
  {
    label: '密码',
    field: 'password',
    type: 'text',
    value: '',
    desc: '',
    required: true,
    search: true,
  },
  {
    label: '多点登陆标识 0单点登录 1多点登录',
    field: 'multiLoginFlag',
    type: 'text',
    value: '',
    desc: '',
    required: true,
    search: true,
  },
  {
    label: '姓名',
    field: 'name',
    type: 'text',
    value: '',
    desc: '',
    required: true,
    search: true,
  },
  {
    label: '邮箱',
    field: 'email',
    type: 'text',
    value: '',
    desc: '',
    required: true,
    search: true,
  },
  {
    label: '电话',
    field: 'phone',
    type: 'text',
    value: '',
    desc: '',
    required: true,
    search: true,
  },
  {
    label: '用户头像',
    field: 'headIcon',
    type: 'text',
    value: '',
    desc: '',
    required: true,
    search: true,
  },
  {
    label: '是否可登录，0-可登陆，1-禁用',
    field: 'loginFlag',
    type: 'text',
    value: '',
    desc: '',
    required: true,
    search: true,
  },
  {
    label: '备注信息',
    field: 'remarks',
    type: 'text',
    value: '',
    desc: '',
    required: true,
    search: true,
  },
  {
    label: '删除标记',
    field: 'delFlag',
    type: 'text',
    value: '',
    desc: '',
    required: true,
    search: true,
  },
  {
    label: '绑定钉钉用户id',
    field: 'bindDingTalkId',
    type: 'text',
    value: '',
    desc: '',
    required: true,
    search: true,
  },
];
export const TableColumns = [
  {
    field: 'kid',
    title: 'ID',
    hide: true,
    sort: false,
    key: 'kid',
    dataIndex: 'kid',
    templet: '',
    toolbar: '#tool-ops',
    minWidth: 140,
    render: 'test',
  },
  {
    field: 'loginName',
    title: '登录名',
    hide: null,
    sort: null,
    key: 'loginName',
    dataIndex: 'loginName',
    templet: '',
    toolbar: null,
    minWidth: null,
    render: null,
  },
  {
    field: 'password',
    title: '密码',
    hide: null,
    sort: null,
    key: 'password',
    dataIndex: 'password',
    templet: '',
    toolbar: null,
    minWidth: null,
    render: null,
  },
  {
    field: 'multiLoginFlag',
    title: '多点登陆标识 0单点登录 1多点登录',
    hide: null,
    sort: null,
    key: 'multiLoginFlag',
    dataIndex: 'multiLoginFlag',
    templet: '',
    toolbar: null,
    minWidth: null,
    render: null,
  },
  {
    field: 'name',
    title: '姓名',
    hide: null,
    sort: null,
    key: 'name',
    dataIndex: 'name',
    templet: '',
    toolbar: null,
    minWidth: null,
    render: null,
  },
  {
    field: 'email',
    title: '邮箱',
    hide: null,
    sort: null,
    key: 'email',
    dataIndex: 'email',
    templet: '',
    toolbar: null,
    minWidth: null,
    render: null,
  },
  {
    field: 'phone',
    title: '电话',
    hide: null,
    sort: null,
    key: 'phone',
    dataIndex: 'phone',
    templet: '',
    toolbar: null,
    minWidth: null,
    render: null,
  },
  {
    field: 'headIcon',
    title: '用户头像',
    hide: null,
    sort: null,
    key: 'headIcon',
    dataIndex: 'headIcon',
    templet: '',
    toolbar: null,
    minWidth: null,
    render: null,
  },
  {
    field: 'loginFlag',
    title: '是否可登录，0-可登陆，1-禁用',
    hide: null,
    sort: null,
    key: 'loginFlag',
    dataIndex: 'loginFlag',
    templet: '',
    toolbar: null,
    minWidth: null,
    render: null,
  },
  {
    field: 'remarks',
    title: '备注信息',
    hide: null,
    sort: null,
    key: 'remarks',
    dataIndex: 'remarks',
    templet: '',
    toolbar: null,
    minWidth: null,
    render: null,
  },
  {
    field: 'delFlag',
    title: '删除标记',
    hide: null,
    sort: null,
    key: 'delFlag',
    dataIndex: 'delFlag',
    templet: '',
    toolbar: null,
    minWidth: null,
    render: null,
  },
  {
    field: 'bindDingTalkId',
    title: '绑定钉钉用户id',
    hide: null,
    sort: null,
    key: 'bindDingTalkId',
    dataIndex: 'bindDingTalkId',
    templet: '',
    toolbar: null,
    minWidth: null,
    render: null,
  },
  {
    field: 'createDate',
    title: '创建时间',
    hide: null,
    sort: null,
    key: 'createDate',
    dataIndex: 'createDate',
    templet: '',
    toolbar: null,
    minWidth: null,
    render: null,
  },
  {
    field: 'createUserId',
    title: '创建人',
    hide: null,
    sort: null,
    key: 'createUserId',
    dataIndex: 'createUserId',
    templet: null,
    toolbar: null,
    minWidth: null,
    render: null,
  },
  {
    field: null,
    title: '操作',
    hide: null,
    sort: null,
    key: 'operation',
    dataIndex: 'operation',
    templet: null,
    toolbar: '#tool-ops',
    minWidth: 140,
    render: 'test',
  },
];
export const title = '熊勇';
export const domain = 'https://api-dev.yryz.com/gateway';
export const serviceName = '/platform-support/v1.0';
export const resourceName = 'manager-accounts';
