export default [
  {
    path: '/login',
    component: '@/pages/login/index',
    headerRender: false,
    footerRender: false,
    menuRender: false,
    name: 'login',
  },
  {
    path: '/demo',
    code: 'demo',
    name: 'demo',
    title: 'demo',
    routes: [
      {
        path: '/demo/demo-1',
        code: 'demo-1',
        component: '@/pages/demo/demo-1',
        name: 'demo-1',
        title: 'demo-1',
      },
      {
        path: '/demo/demo-2',
        code: 'demo-2',
        component: '@/pages/demo/demo-2',
        name: 'demo-2',
        title: 'demo-2',
      },
      {
        path: '/demo/demo-3',
        code: 'demo-3',
        hideInMenu: true,
        component: '@/pages/demo/demo-3',
        name: 'demo-3',
        title: 'demo-3',
      },
    ],
  },
  {
    path: '/manange',
    code: 'manange',
    name: 'manange',
    title: 'manange',
    routes: [
      {
        path: '/manange/users',
        code: 'users-list',
        component: '@/pages/manange/users/index',
        name: 'users-列表',
        title: '用户-列表',
      },
      {
        path: '/manange/users/detail',
        code: 'users-detail',
        component: '@/pages/manange/users/detail',
        name: 'users-详情',
        hideInMenu: true,
        title: '用户-详情',
      },
      {
        path: '/manange/users/form',
        code: 'users-form',
        component: '@/pages/manange/users/form',
        name: 'users-表单',
        hideInMenu: true,
        title: '用户-表单',
      },
    ],
  },
];
